replicaCount: 1

image:
  repository: ollama/ollama
  tag: "aa8f1792"
  pullPolicy: IfNotPresent

model:
  name: "tinyllama"
  servedName: "llm"
  swapSpace: 0

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "3Gi"
    cpu: "2000m"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
     drop:
       - ALL

service:
   type: ClusterIP
   port: 11434

ingress:
   enabled: true
   host: "llm-platform.duckdns.org"
   clusterIssuer: "letsencrypt-prod"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

networkPolicy:
   enabled: false

prometheusRule: 
  enabled: true



env:
  - name: OLLAMA_MODELS
    value: "/tmp/models"
  - name: HOME
    value: "/tmp"
