{{- if .Values.prometheusRule.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: vllm-slo-alerts
    namespace: {{ .Release.Namespace }}
    labels:
        release: kube-prometheus-stack
spec:
    groups:
    - name: vllm.slo
      interval: 30s
      rules:
      - alert: LLMHighLatencyP95
        expr: |
            histogram_quantile(0.95,rate(vllm:e2e_request_latency_seconds_bucket[5m])) > 15
        for: 5m
        labels:
            severity: warning
            team: platform
        annotations:
            summary: "vLLM P95 latency {{ "{{" }} $value | humanizeDuration {{ "}}" }} exceeds 15s  SLO"
            runbook: "https://github.com/ambawatyuvaraj/llm-platform/wiki/runbooks"
      - alert: LLMRequestQueueBacklog
        expr: vllm:num_requests_waiting > 15
        for: 2m
        labels:
            severity: critical
            team: platform
        annotations:
            summary: "{{ "{{" }} $value {{ "}}" }} requests queued - scale up or investigate"
      - alert: LLMPodCrashLooping
        expr: | 
            rate(kube_pod_container_status_restarts_total{namespace="{{ .Release.Namespace }}"}[5m]) > 0
        for: 1m
        labels:
            severity: critical
            team: platform
        annotations:
            summary: "vLLM pod {{ "{{" }} $labels.pod {{ "}}" }} is crash-looping"

{{- end}}