apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-vllm
    namespace: {{ .Release.Namespace }}
    labels:
        app: vllm
spec:
    type: {{ .Values.service.type }}
    ports:
    - port: {{  .Values.service.port }}
      targetPort: 11434
      protocol: TCP
      name: http
    selector:
        app: vllm